"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { runReportGeneration } from "@/app/admin/actions";
import type { GeneratedReport } from "@/lib/report-generation";

type Row = {
  id: string;
  title: string;
  company: string;
  tier: string;
  ownerEmail: string;
  supportingCount: number;
};

type RowState =
  | { status: "idle" }
  | { status: "running" }
  | { status: "done"; report: GeneratedReport }
  | { status: "error"; error: string };

export function AdminReviewList({ initialRows }: { initialRows: Row[] }) {
  const [rowStates, setRowStates] = useState<Record<string, RowState>>({});

  async function handleRun(id: string) {
    setRowStates((prev) => ({ ...prev, [id]: { status: "running" } }));
    const result = await runReportGeneration(id);
    if (!result.ok) {
      setRowStates((prev) => ({
        ...prev,
        [id]: { status: "error", error: result.error },
      }));
      return;
    }
    setRowStates((prev) => ({
      ...prev,
      [id]: { status: "done", report: result.data },
    }));
  }

  if (initialRows.length === 0) {
    return (
      <p className="text-[14.5px] text-cream-400">
        No transcribed requests waiting on report generation.
      </p>
    );
  }

  return (
    <div className="space-y-4">
      {initialRows.map((row) => {
        const state = rowStates[row.id] ?? { status: "idle" };
        return (
          <div
            key={row.id}
            className="rounded-md border border-cream-200/10 bg-ink-850 p-6"
          >
            <div className="flex flex-wrap items-center justify-between gap-4">
              <div>
                <p className="font-mono text-[10.5px] uppercase tracking-[0.08em] text-rust-400">
                  {row.tier}
                </p>
                <h3 className="mt-1 font-serif text-lg text-cream-100">
                  {row.title}
                </h3>
                <p className="mt-1 text-[13px] text-cream-400">
                  {row.company} · {row.ownerEmail}
                </p>
                {row.supportingCount > 0 && (
                  <p className="mt-1 font-mono text-[11px] text-rust-400">
                    + {row.supportingCount} supporting doc
                    {row.supportingCount === 1 ? "" : "s"}
                  </p>
                )}
              </div>

              <Button
                size="sm"
                disabled={state.status === "running"}
                onClick={() => handleRun(row.id)}
              >
                {state.status === "running"
                  ? "Generating…"
                  : state.status === "done"
                    ? "Re-generate report"
                    : "Generate report"}
              </Button>
            </div>

            {state.status === "error" && (
              <p className="mt-4 rounded border border-rust-400/30 bg-rust-400/5 px-4 py-3 text-[13px] text-rust-400">
                {state.error}
              </p>
            )}

            {state.status === "done" && (
              <div className="mt-4 rounded border border-green-400/20 bg-green-400/5 p-4">
                <p className="font-mono text-[10.5px] uppercase tracking-[0.08em] text-green-400">
                  Report drafted · status: DRAFT · generated by:{" "}
                  {state.report.generatedBy}
                </p>
                <pre className="mt-3 max-h-96 overflow-y-auto whitespace-pre-wrap break-words rounded bg-ink-900 p-3 text-[11.5px] leading-relaxed text-cream-300">
                  {JSON.stringify(state.report, null, 2)}
                </pre>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
